큐레이션 상세 페이지의 메인 이미지뷰를 만들었습니다.
DeveloperAcademy-POSTECH/MacC-Team-Sandals pull request #2
Opened 2022-10-19 07:55 UTC by im-niber

# 배경

노션에 적은대로 위에 있는 이미지 뷰와 아래에 있는 컬렉션뷰로 뷰를 나눠서 개발을 진행하고 있습니다. 

# 작업 내용

- 더미데이터 사진을 하나 추가했습니다.
- UIView 내부에 이미지와 라벨 두개를 넣어서 개발을 하였습니다.
- 그라데이션 로직을 UIViewController+ 파일에 만들어서 나중에도 재사용 가능하게 하였습니다.

> 아직 정확한 색깔, 마진, 폰트 등은 모르기 때문에 해당 부분들이 결정이 되면 수정해서 다시 올리겠습니다.

# 스크린샷
<img width="392" alt="image" src="https://user-images.githubusercontent.com/66784492/196629791-c8ece443-6e84-4534-83e3-3bf0bc01d534.png">

2022-10-19 08:19 UTC, stemmmm requested changes
좀 많은데 초반이라 그런듯합니당 ㅎㅎ

2022-10-19 08:19 UTC, stemmmm commented on Kindy/Kindy/SceneDelegate.swift
> +        /// Test Code 사용방법
[S2] 이 커밋은 다들 보시면 좋을것 같은데 따로 PR 해주실 수 있나요?

2022-10-19 08:19 UTC, stemmmm commented on Kindy/Kindy/Controllers/CurationViewController.swift
> +    override func viewDidAppear(_ animated: Bool) {
[S3- 그냥 궁금해용] `viewDidAppear`에서 `configureGradient()`하신 이유가 있나요?

2022-10-19 08:19 UTC, stemmmm commented on Kindy/Kindy/Controllers/CurationViewController.swift
> +            mainView.rightAnchor.constraint(equalTo: view.rightAnchor),
[S1] `rightAnchor`와 `leftAnchor` 대신에 `leadingAnchor`와 `trailingAnchor`를 쓰시는건 어떠신지요?

2022-10-19 08:19 UTC, stemmmm commented on Kindy/Kindy/Views/Curation/CurationMainView.swift
> +    // Model이 들어오면 수정해야함
[S3] `// TODO:` 주석을 사용해보는것도 좋을것같아요

2022-10-19 08:19 UTC, stemmmm commented on Kindy/Kindy/Views/Curation/CurationMainView.swift
> +
[S1] 전체적인 프로퍼티들의 네이밍에 관련해서 얘기해봐야할 것 같네용
(예를들어, `title` vs `titleLabel` 중 어떤 형태로 쓸까요)

2022-10-19 08:19 UTC, stemmmm commented on Kindy/Kindy/Views/Curation/CurationMainView.swift
> +    private lazy var mainImage: UIImageView = {
[S1] 프로퍼티 선언도 얘기하면 좋을것 같아요
1. 내부에서 모두 `view`로 선언하셨는데 그것보다는 더 잘 나타내는 이름은 어떤지요?
(e.g. `view` 대신 `imageView`
2. `translateAutoResi-`을 어디에서 선언할 것인지
3. 추가로 private과 lazy의 사용 의도가 궁금합니다

2022-10-19 08:19 UTC, stemmmm commented on Kindy/Kindy/Views/Curation/CurationMainView.swift
> +    override init(frame: CGRect) {
[S1] `self` 와 같은 이런 코딩 컨벤션에 관해서 얘기하면 좋을것 같네용

2022-10-19 08:22 UTC, im-niber commented on Kindy/Kindy/Controllers/CurationViewController.swift
> +    override func viewDidAppear(_ animated: Bool) {
오토레이아웃 잡고나서 따로 함수 만들어서 viewDidLoad에 넣었는데 동작을 안해서 viewDidAppear에 넣으니 동작하더라구여 print 찍어보니 view.bounds가 0으로 계산되서 viewDidAppear에 넣어야 할 것 같습니다. 좀 더 알아봐야겠지만 다른 방법도 있을거같아여

2022-10-19 08:23 UTC, im-niber commented on Kindy/Kindy/Controllers/CurationViewController.swift
> +            mainView.rightAnchor.constraint(equalTo: view.rightAnchor),
좋습니당  !
[S3] 근데 혹시 어떤점이 다른가여  ? ?

2022-10-19 08:23 UTC, im-niber commented on Kindy/Kindy/Views/Curation/CurationMainView.swift
> +    // Model이 들어오면 수정해야함
확실히 보기 더 좋을 듯 good

2022-10-19 08:23 UTC, im-niber commented on Kindy/Kindy/Views/Curation/CurationMainView.swift
> +
그렇네요 이거 제가 맞출게요 말씀해주십쇼

2022-10-19 10:17 UTC, im-niber commented on Kindy/Kindy/Views/Curation/CurationMainView.swift
> +    private lazy var mainImage: UIImageView = {
> 아까 얘기한 부분에서 제가 생각한 부분들만 적을게용
1. 실제 사용할 프로퍼티 이름과 타입에서 이미 얘가 어떤 역할을 하는지 드러나있다고 생각을해서 내부에는 간편하게 view로 적었습니다.
2. 저는 보통 프로퍼티 선언하면서 같이 작성하는편입니다 ! 
3. private는 성능의 이점이 있다고 알고 있어서 사용을 하고 lazy를 사용하는 이유를 들었는데,, 까먹어버렸네요 ㅜㅡㅜ 한 번 찾아보겠습니다

2022-10-19 11:19 UTC, stemmmm commented on Kindy/Kindy/Controllers/CurationViewController.swift
> +            mainView.rightAnchor.constraint(equalTo: view.rightAnchor),
left = 왼쪽
leading = 글이 시작하는 지점(우리나라의 경우 left와 leading이 같지만, 아랍권의 경우 반대입니다)

2022-10-20 07:27 UTC, rkddnr330 reviewed
👍🏼

2022-10-20 07:27 UTC, rkddnr330 commented on Kindy/Kindy/SceneDelegate.swift
> +        /// Test Code 사용방법
[S2] 네비게이션 바가 필요하신 분은 밑의 코드로 넣으시면 됩니다.
`window?.rootViewController = UINavigationController(rootViewController: 자신의 뷰())`

2022-10-20 07:28 UTC, merged