큐레이션 상세 페이지에 댓글 기능을 구현했습니다
DeveloperAcademy-POSTECH/MacC-Team-Sandals pull request #71
Opened 2022-11-23 16:26 UTC by im-niber

# 배경
- 큐레이션 상세 페이지 내부에 댓글 기능을 구현해야합니다.

# 작업 내용

- 큐레이션 댓글 버튼 UI 구현
- 큐레이션 댓글 셀 구현
- 큐레이션 댓글 추가, 삭제 로직 구현
    - 삭제는 셀을 꾹 누르면 삭제 알림창을 present 
- 유저 DocumentID fetch 함수 구현
- 바텀시트가 확장 상태일 때 아래로 드래그 하면 뷰 dismiss 기능 구현

# 스크린샷

https://user-images.githubusercontent.com/66784492/203597731-a86a9176-6664-411f-bffc-09728fab5dce.mov

2022-11-23 16:55 UTC, im-niber reviewed
파이어비이스으립네 ~

2022-11-23 16:55 UTC, im-niber commented on Kindy/Kindy/Extensions/Reportable+.swift
>          let alertController = UIAlertController(title: nil, message: nil, preferredStyle: style)
신고 버튼을 누르면 실행되는 함수입니다. 신고가 alert을 3번정도 띄우는 형식이다 보니, 키보드를 dismiss하지 않으면 계속 띄워졌다가 내려지고 그래서 여기서도 `hideKeyboard`를 추가하였습니다.

2022-11-23 16:55 UTC, im-niber commented on Kindy/Kindy/Views/Curation/CurationCommentTextFieldCell.swift
> +}
텍스트 필드 delegate가 아닌 버튼으로 이벤트를 감지하도록 설정하였습니다.
이런 방식도 있어서 그냥 사용해보았습니다 ㅎ,ㅎ iOS14 부터는 `addAction(_:for:)`도 있다고 하네요

https://kirkim.github.io/swift/2021/12/11/backspace.html

요거 잘 나와있슴다

2022-11-23 16:55 UTC, im-niber commented on Kindy/Kindy/Models/Comment.swift
> +}
`userID`를 맨 처음 fetch를 해서 가지고 있다가 댓글이 보이기전에 `userID`로 닉네임을 검색해와서 구조체에 넣는 형식으로 구현을 하였습니다. 닉네임 변경을 해도 이제 본인이 작성한지 아닌지가 쉽게 확인이 가능합니다.

2022-11-23 16:55 UTC, im-niber commented on Kindy/Kindy/View Controllers/Curation/CurationViewController.swift
> +    }
피드백을 반영하였슴다 ㅎ,ㅎ
`willAppear`에서 fetch 해오는 방식으로 바꾸었고, 내부에서 닉네임까지 다 받은 다음에 컬렉션 뷰를 업데이트를 해줍니다
`listner`를 설정한 이유는 나중 커밋에 `fetchComments`에 적어두겠습니당

2022-11-23 16:55 UTC, im-niber commented on Kindy/Kindy/Network Controllers/CurationRequest.swift
> +            completion(querySnapshot,error)
댓글을 구현하면서 고민했던 부분인데, 댓글을 추가, 삭제시에 fetch를 해와야 한다고 생각했습니다(다른 누군가가 그 사이에 업데이트를 했을수도 있으니가~?) 

그렇게 결론을 내리고 그러면 파이어베이스에서 댓글들을 다시 다 읽어와야 하는건 비효율적이라고 생각이 들어서 내가 가지고 있는 댓글들과 서버에 있는걸 비교해서 fetch 해와야겠다 라고 생각했는데 좀 찾아보니 `addSnapshotListener`라는 친구가 있더라구요

이 친구는 컬렉션에 걸어주면 관찰하고 있다가 컬렉션 내부가 변경이 되면 실행이되는 함수입니다. (지금 completion 보이시죠~?)
그래서 댓글이 삭제되거나 추가되어도 알아서~ 실행이 됩니다 매우 착한친구죠

이 친구가 수신하는걸 나중에는 끊어야하니까 위(큐레이션 뷰컨)에서 `listener`를 만들어서 할당해줬습니다. 그리고 뷰가 사라질 때 `nil`을 하였는데,, 사실 이게 맞게 하는지는 잘 모르겠슴다 ㅜㅡㅜ 

미리 `listener`에 타입을 제대로 주고 싶은데 먼가 잘 안되어서 일단 `Any`로 주고 진행했슴다.. 아시는 분이 있다면 help..

2022-11-24 03:05 UTC, stemmmm requested changes
고생하셨습니다~ 😀

2022-11-24 03:05 UTC, stemmmm commented on Kindy/Kindy/Extensions/Reportable+.swift
>          let alertController = UIAlertController(title: nil, message: nil, preferredStyle: style)
[s3] 생각해보니 이 파일은 프로토콜의 extension이라 굳이 따로 안빼고 protocol 파일 내부에 쓰셔도 괜찮을듯용?

2022-11-24 03:05 UTC, stemmmm commented on Kindy/Kindy/Models/Curation/Comment.swift
> +//  Created by rbwo on 2022/11/21.
컷~

2022-11-24 03:05 UTC, stemmmm commented on Kindy/Kindy/Models/Curation/Comment.swift
> +    var createdAt: Date = Date()
[s999] 타입 추론 빼도 될것같네용

2022-11-24 03:05 UTC, stemmmm commented on Kindy/Kindy/Network Controllers/UserManager.swift
> +    }
이 메서드가 필요하다면 이제 UserManager도 FirestoreRequest 프로토콜을 채택하면 되겠네용! 그럼 이 함수는 구현 안해도 됩니다~

+ 어제 했던 이야기에서 좀 더 생각해봤는데 유저의 데이터를 나중에 리팩토링할때 UserDefault에 넣는것은 어떠신지?

2022-11-24 03:05 UTC, stemmmm commented on Kindy/Kindy/Network Controllers/CurationRequest.swift
> +            completion(querySnapshot,error)
맞아용
파이어베이스에 따르면 기본적으로는 매번 fetch 하는 것보다 listener를 사용하는 것을 권장하고 있습니당
저도 이 사실을 다 구현한 다음 알게돼서... 나중에 바꿔볼까 생각중이긴했어요

listener 관련한 부분은 큐레이션 뷰컨에 남겨두겠습니당~

2022-11-24 03:05 UTC, stemmmm commented on Kindy/Kindy/View Controllers/Curation/CurationViewController.swift
> +    private var listener: Any?
[s2] listener는 ListenerRegisteration 타입입니당~

2022-11-24 03:05 UTC, stemmmm commented on Kindy/Kindy/View Controllers/Curation/CurationViewController.swift
> +    }
[s2] 지금 구조를 보면 컴플리션의 컴플리션으로 넘겨받는 형태인것 같은데, 혹시 fetchComments 함수를 이런 느낌으로 하면 어떠신지? (간단하게 생각한거라 잘 안될지도 모릅니다)
```
func addListener() -> [Type] {
    db.collection(collectionPath).addSnapshotListener { querySnapshot, error in
        // 에러 처리...

        return querySnapshot?.documents.map { $0.data(as: Type.self) }
    }
}
```

2022-11-24 03:05 UTC, stemmmm commented on Kindy/Kindy/View Controllers/Curation/CurationViewController.swift
> +        listener = nil
[s1] `nil`을 할당하는 것보다는 `.remove()`를 사용하시면 될 것 같슴다

2022-11-24 04:29 UTC, im-niber commented on Kindy/Kindy/View Controllers/Curation/CurationViewController.swift
> +    private var listener: Any?
yes 하지만 여기 뷰컨에서 타입을 선언하려고 했는데 그러려면 import 해와야해서 Any로 받았습니다 이 부분을 한번 얘기해보고싶었슴당

2022-11-24 04:31 UTC, im-niber commented on Kindy/Kindy/View Controllers/Curation/CurationViewController.swift
> +        listener = nil
remove 쓰고 싶지만,, 타입을 명시하는게 안되어서ㅜㅜ,, 위에 적은 이유랑 같습니다

2022-11-24 04:31 UTC, profit0124 approved these changes
확인했습니다.

2022-11-24 04:31 UTC, profit0124 commented on Kindy/Kindy/View Controllers/Curation/CurationViewController.swift
> +                   index += 1
[s3] 이 부분을 map으로 표현을 하면 index 계산을 하지 않아도 될 것 같습니다.

2022-11-24 04:31 UTC, profit0124 commented on Kindy/Kindy/View Controllers/Curation/CurationViewController.swift
> +    }
[s3] 한가지 궁금한점이 있습니다. 자기 자신이 작성할때를 제외하고 계속 listener를 통해 값의 변화를 추적하며 변경을 줄 필요가 있을까요?

2022-11-24 04:31 UTC, profit0124 commented on Kindy/Kindy/View Controllers/Curation/CurationViewController.swift
> +            self.hideKeyboard()
[s3]hide keyboard 보단 textfield의 포커스를 해제하는게 더 확실하지 않을까요? textfield가 하나이니.resignFirstRespond()?

2022-11-24 04:35 UTC, im-niber commented on Kindy/Kindy/View Controllers/Curation/CurationViewController.swift
> +    }
`addSnapshotListener`를 뷰컨에서 확인을 해서 뷰를 변경하고 싶어서 일부러 completion으로 인자를 받는식으로 구현했는데 요거로도 해결이 된다면 나중에 칸반회의 끝나고 같이 얘기하심가 잘 모르겠으,,,

2022-11-24 04:41 UTC, im-niber commented on Kindy/Kindy/View Controllers/Curation/CurationViewController.swift
> +            self.hideKeyboard()
오 생각을 못했는데 그게 더 좋은거 같슴다 ! 반영할게여

2022-11-24 04:42 UTC, im-niber commented on Kindy/Kindy/View Controllers/Curation/CurationViewController.swift
> +                   index += 1
`map` 으로 하려니가 원래 `curation.comments` 내부를 변경하는거다 보니 `let`으로 인자를 받아서 잘 안되어서 이렇게 했는데,,,  나중에 알려주심가

2022-11-24 04:44 UTC, im-niber commented on Kindy/Kindy/View Controllers/Curation/CurationViewController.swift
> +    }
> [s3] 한가지 궁금한점이 있습니다. 자기 자신이 작성할때를 제외하고 계속 listener를 통해 값의 변화를 추적하며 변경을 줄 필요가 있을까요?

그래서 한 번 얘기해보려고 했슴다 아마 다른 사람이 댓글달면 갑자기 내 디바이스에서도 업데이트 될 거 같은데 이 부분도 눈으로 확인해보고 싶어서 ㅋㅌㅋ 채팅에만 써야하나 싶기도 하고 .. ?

2022-11-24 04:47 UTC, im-niber commented on Kindy/Kindy/Network Controllers/UserManager.swift
> +    }
ㅇㅎ 좋슴다 채택시켜서 하는걸로 ~
`UserDefault`에 넣어도 좋을거같은데 얘기해보져 뭐든 유저의 정보를 전역적으로 확인하는 매니저? 가 있었으면 했던거라서 ~

2022-11-24 05:55 UTC, stemmmm commented on Kindy/Kindy/View Controllers/Curation/CurationViewController.swift
> +    private var listener: Any?
import 자체는 컴파일 타임에 영향을 미치는것 같아서 큰 문제는 없을 것 같습니다~
[관련 링크](https://stackoverflow.com/questions/49652304/do-import-statements-in-swift-have-an-associated-cost)

2022-11-24 05:59 UTC, rkddnr330 requested changes
고생하셨습니다 🔥

2022-11-24 05:59 UTC, rkddnr330 commented on Kindy/Kindy/Views/Curation/CurationButtonItem.swift
> +protocol ReplyButtonAction: AnyObject {
[S2] `Reply`와 `Comment`가 차이가 있는 게 아니라면, 네이밍을 `Reply` -> `Comment`로 통일하는 게 어떨까요 ?

2022-11-24 06:05 UTC, im-niber commented on Kindy/Kindy/Views/Curation/CurationButtonItem.swift
> +protocol ReplyButtonAction: AnyObject {
아 남아있었네요 바꾸겠슴다

2022-11-24 06:46 UTC, rkddnr330 approved these changes

2022-11-24 06:46 UTC, stemmmm approved these changes

2022-11-24 06:46 UTC, merged